# This file sets up the reciever, so it is interpreted correctly.
rx:
  channel_map: AETR1234       # This is the channel mapping
                              # A = Aileron,  roll
                              # E = Elevator, pitch
                              # T = Thrust,   throttle
                              # R = Rudder,   yaw
                              # Number = Aux-Number
  aux_rate: 20.               # The rate at which the aux_channels are checked (Hz)
  aileron:
    min_us: 1000                # Lowest signal the tx sends in microseconds.
    mid_us: 1535                # Middle signal the tx sends in microseconds.
    max_us: 2015                # Longest signal the tx sends in microseconds.
  elevator:
    min_us:  925                # Lowest signal the tx sends in microseconds.
    mid_us: 1396                # Middle signal the tx sends in microseconds.
    max_us: 1912                # Longest signal the tx sends in microseconds.
  thrust:
    min_us:  985                # Lowest signal the tx sends in microseconds.
    mid_us: 1463                # Middle signal the tx sends in microseconds.
    max_us: 1960                # Longest signal the tx sends in microseconds.
  rudder:
    min_us:  925                # Lowest signal the tx sends in microseconds.
    mid_us: 1527                # Middle signal the tx sends in microseconds.
    max_us: 1985                # Longest signal the tx sends in microseconds.

  arming:
    arm_aux_channel: 1        # The auxilary channel used to arm and disarm the vehicle (no matter the channel mapping)
    min_arm_us: 800           # In order for motors to spin, the 'arming/aux_channel' must send a minimum of this us.
    max_arm_us: 1300          # In order for motors to spin, the 'arming/aux_channel' must send a maximum of this us.
    arm_throttle_max: 1005    # In order to arm, aux_channel must be between min_arm_us and max_arm_us and throttle must
                              # be below 'throttle_max'. SET throttle_max no more than 25 above min_us.
  modes:
    mode_aux_channel: 2       # Channel that selects the flight mode.
    min_angle_mode: 1000      # Minimum microseconds for angle mode.
    max_angle_mode: 1350      # Minimum microseconds for angle mode.
    min_rates_mode: 1350      # Minimum microseconds for rates mode.
    max_rates_mode: 1650      # Minimum microseconds for rates mode.
    min_veloc_mode: 1650      # Minimum microseconds for veloc mode.
    max_veloc_mode: 2000      # Minimum microseconds for veloc mode.

    rc_override_channel: 3    # Auxilary channel that determines autonomous flight or rc flight
    min_auto_us: 1500         # Minimum microseconds for autonomous takeover.
    max_auto_us: 2000         # Maximum microseconds for autonomous takeover.
  curve:
    angle_mode:
      max_angle: 60.0         # Maximum angle allowed (positive degrees)
      expo: 0.3               # Expo, 0.0 - 1.0, Higher means flatter near the middle
      super_rate: 0.0         # Super Rate, 0.0 - 1.0, Higher means more extreme away from center
    rate_mode:
      rc: 1.0                 # RC Rate, basic tuning parameter for sensitivity
      expo: 0.3               # Expo, 0.0 - 1.0, Higher means flatter near the middle
      super_rate: 0.0         # Super Rate, 0.0 - 1.0, Higher means more extreme away from center
    thrust:
      rc: 1.0                 # RC Rate, basic tuning parameter for sensitivity
      expo: 0.0               # Expo, 0.0 - 1.0, Higher means flatter near the middle
      super_rate: 0.0         # Super Rate, 0.0 - 1.0, Higher means more extreme away from center
